// `worker-configuration.d.ts` is generated by `wrangler types` from `wrangler.jsonc`, which
// declares only bindings — the vars/secrets live in the Cloudflare dashboard and `.dev.vars`,
// so they can never appear there. `wrangler.test.jsonc` does declare them (as dummies), which
// is why the two configs look mismatched. Tests read `env` from `cloudflare:test`, typed as
// `Cloudflare.Env`, so widen that interface with the Worker's own `Env` — the actual source of
// truth for what the handlers require — instead of casting at each use site.
import type { Env as WorkerEnv } from './index'

declare global {
  namespace Cloudflare {
    interface Env extends WorkerEnv {}
  }
}
